products:
  robo-go:
    build:
      main-pkg: .
      version-var: main.version
      os-archs:
        - os: linux
          arch: arm
        - os: darwin
          arch: amd64
    dist:
      disters:
        os-arch-bin:
          type: os-arch-bin
          config:
            os-archs:
              - os: linux
                arch: arm
              - os: darwin
                arch: amd64
        bin:
          type: bin
